Features/#372 sections memorizing
JetBrains-Research/snakecharm pull request #383
Opened 2021-07-13 13:13 UTC by dakochik

Issue #372 is resolved

2021-07-13 15:30 UTC, iromeo requested changes

2021-07-13 15:30 UTC, iromeo commented on src/main/kotlin/com/jetbrains/snakecharm/inspections/quickfix/AddIgnoredElementQuickFix.kt
> +            model.modifyProfile {
In PyCharm `src/com/jetbrains/python/inspections/quickfix/AddIgnoredIdentifierQuickFix.java` uses shorter solution for this usecase (i.e. `modifyAndCommitProjectProfile()`), please refactor this

2021-07-13 15:30 UTC, iromeo commented on src/main/kotlin/com/jetbrains/snakecharm/inspections/quickfix/AddIgnoredElementQuickFix.kt
> +            TemplateBuilderImpl(startElement).run(editor!!, false)
Why do we need this? E.g. `src/com/jetbrains/python/inspections/quickfix/AddIgnoredIdentifierQuickFix.java` doesn't have such code

2021-07-13 15:30 UTC, iromeo commented on src/main/kotlin/com/jetbrains/snakecharm/inspections/quickfix/AddIgnoredElementQuickFix.kt
> +    private val elementName = element.text
Do we need here `LocalQuickFixAndIntentionActionOnPsiElement(element)` ? Could we use just ` implements LocalQuickFix, LowPriorityAction` ?

2021-07-13 15:30 UTC, iromeo commented on src/main/kotlin/com/jetbrains/snakecharm/inspections/quickfix/AddIgnoredElementQuickFix.kt
> +    private val elementName = element.text
Is `elementName` is section name? If yes, please use user-friendly variable name naming

2021-07-13 15:30 UTC, iromeo commented on src/main/kotlin/com/jetbrains/snakecharm/inspections/quickfix/AddIgnoredElementQuickFix.kt
> +            val text = startElement.text
is here text is same as `private val elementName = element.text` field? if yes, please use `elementName`

2021-07-13 20:55 UTC, dakochik commented
refactored AddIgnoredElementQuickFix.kt code:
1) start using appropriate methods
2) change list of inherited classes
3) makes code meets Kotlin code style conventions
4) removes useless checks

![memorizing](https://user-images.githubusercontent.com/55440084/125523515-4338e856-fb3b-4aee-ad31-94071e719e10.gif)

2021-07-13 21:20 UTC, iromeo requested changes
Some minor code improvements still required

2021-07-13 21:20 UTC, iromeo commented on src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkUnrecognizedSectionInspection.kt
> +        return ListEditForm(
Please reformat according to Kotlin code style conventions:
> Prefer using an expression body for functions with the body consisting of a single expression.

See https://kotlinlang.org/docs/coding-conventions.html#functions

2021-07-13 21:20 UTC, iromeo commented on src/main/kotlin/com/jetbrains/snakecharm/inspections/quickfix/AddIgnoredElementQuickFix.kt
> +    private val sectionName = section.text
`section: PsiElement` used only once for private field initialization, let's simply constructor to `class AddIgnoredElementQuickFix(private val sectionName: String)`

2021-07-14 06:08 UTC, dakochik commented
refactored: 
1) simplifies AddIgnoredElementQuickFix.kt constructor
2) makes SmkUnrecognizedSectionInspection.kt code meets Kotlin code style conventions

2021-07-14 14:11 UTC, iromeo requested changes
Minor code change still required

2021-07-14 14:11 UTC, iromeo commented on src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkUnrecognizedSectionInspection.kt
> +                    null, AddIgnoredElementQuickFix(sectionNamePsi.text)
The section name is already stored in `sectionKeyword` variable, please use it instead

2021-07-14 14:11 UTC, iromeo commented on src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkUnrecognizedSectionInspection.kt
> +                    null, AddIgnoredElementQuickFix(sectionNamePsi.text)
The section name is already stored in `sectionKeyword` variable, please use it instead

2021-07-14 14:54 UTC, dakochik commented
refactored: makes function call more readable

2021-07-14 15:07 UTC, merged