Issue is resolved
JetBrains-Research/snakecharm pull request #391
Opened 2021-07-22 08:29 UTC by dakochik

Issue #384 is resolved

2021-07-26 16:35 UTC, iromeo requested changes
Workflow and rule/checkpoint names should be decoupled + please fix also `SmkSyntaxErrorAnnotator` to highlight as error:
```
wildcard_constraints:
    foo = ".*",
    foo = ".*"
```

2021-07-26 16:35 UTC, iromeo commented on src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSectionUnexpectedKeywordArgsInspection.kt
> +            if (st.sectionKeyword in SECTIONS_WHERE_KEYWORD_ARGS_PROHIBITED) {
You check workflow top-level section name in list of rule/checkpoint section names. Here should be 2 different lists, one for rule/checkpoint set, the other for workflow top level sections. E.g. for 'container' we have SnakemakeNames.WORKFLOW_CONTAINER_KEYWORD and SnakemakeNames.CONTAINER_KEYWORD.

2021-07-26 16:35 UTC, iromeo commented on src/main/kotlin/com/jetbrains/snakecharm/inspections/SmkSectionMultipleArgsInspection.kt
> +            if (name != null && name in SINGLE_ARGUMENT_SECTIONS_KEYWORDS) {
Same comment as in SmkSectionUnexpectedKeywordArgsInspection

2021-07-27 09:12 UTC, dakochik commented
fixed: highlighting for SmkSyntaxErrorAnnotator
refactored: separate sections for workflows keywords are created

2021-07-27 16:46 UTC, merged