Features/#277 create missing env file
JetBrains-Research/snakecharm pull request #445
Opened 2021-12-02 17:26 UTC by dakochik

Quick fix for missing `.yaml` / `.yml` file was implemented.

2021-12-03 11:24 UTC, iromeo requested changes

2021-12-03 11:24 UTC, iromeo commented on src/main/kotlin/com/jetbrains/snakecharm/inspections/quickfix/CreateEnvFile.kt
> +            tokens.forEach {
It is reasonable to expect, that in such complicated application, like IntelliJ platform the task of creating file by relative path + create intermediate dirs isn't a rare case and already solved via some API. The code below is bicycle invention in a rather complected way. E.g. java.io already have methods for creating files and folders. So here we could use smth like: 

```kotlin
        val targetFile = file.virtualFile.parent.findFileByRelativePath(fileName)
        // if targetFile == null ....
        val targetFileFolder = targetFile.parent
        VfsUtil.createDirectoryIfMissing(targetFileFolder.path)
        LocalFileSystem.getInstance().createChildFile(this, targetFileFolder, targetFile.name)
```

or just:
```kotlin
        val targetFile = Paths.get(file.virtualFile.parent.path, fileName)
        Files.createDirectories(targetFile.parent)
        Files.createFile(targetFile)
```

2021-12-03 11:24 UTC, iromeo commented on CHANGELOG.md
> +- Quick fix for unresolved '.yaml' / '.yml' files (see [#277](https://github.com/JetBrains-Research/snakecharm/issues/277))
Also could you please extend this feature not only on `conda:` section, but also for other places where we add similar file reference.

2021-12-03 11:30 UTC, iromeo commented
Also it is good to make this action undoable, try to use UndoableAction interface.

2021-12-03 11:31 UTC, iromeo commented
Allows to create files without YAML / YML / yaml / yml suffix, e.g. `envs/ddd/ddd/dddaaaa` , i think that better to forbid this and show error

2021-12-03 11:34 UTC, iromeo commented
Error should like failed to created `/ednvs/...` file, not `untiled10`
![image](https://user-images.githubusercontent.com/72933/144595945-8324ed87-aca4-4f24-b6ad-769520e93e7b.png)

2021-12-18 19:59 UTC, iromeo reviewed
Let's disscuss some impl details + need to fix absolute paths issue. Optionally you could file a new issue for abs path support and do not include it into this PR.

2021-12-18 19:59 UTC, iromeo commented on src/main/kotlin/com/jetbrains/snakecharm/inspections/quickfix/CreateMissedFile.kt
> +                VirtualFileManager.getInstance().asyncRefresh { }
Also, not sure that we need to interact with Virtual File System here. 'undo' uses just "java.io.File" standard Java SDK API. Here maybe is better to check existence/create file w/o using VFS api, refresing, etc.

2021-12-18 19:59 UTC, iromeo commented on src/main/kotlin/com/jetbrains/snakecharm/inspections/quickfix/CreateMissedFile.kt
> +        val relativeDirectory =
Fix doesn't work ok if absolute path is used, e.g.:


```
rule rule277_s:
    conda: "/ednvs/ddd/ddd/dddaaaa.yaml"
    script: "env/ddddd.py"
```

on runtime expects absolute path:
```
$ snakemake --snakefile rule277.smk --use-conda -c1
Building DAG of jobs...
WorkflowError:
Failed to open source file /ednvs/ddd/ddd/dddaaaa.yaml
FileNotFoundError: [Errno 2] No such file or directory: '/ednvs/ddd/ddd/dddaaaa.yaml'
```

but quick fixes tries to create a file in project working directory. I assume that it valid for all file references for conda, script, etc sections. E.g. path could be absolute or relative. Is better to check.

2021-12-24 13:12 UTC, dakochik commented
Discussed problems were solved.

2022-01-15 15:46 UTC, merged